import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Navbar, ScrollDisabler } from "./components";

const inter = Montserrat({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Lorenz Naegele",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ScrollDisabler />

      <body className={`${inter.className} h-svh w-svw `}>
        <Navbar />
        <main className="">{children}</main>
      </body>
    </html>
  );
}
