import type { Metadata } from "next";
import "./globals.css";
import { Navbar, ScrollDisabler } from "./components";
import { mainFont } from "./lib/font";

export const metadata: Metadata = {
  title: "Lorenz Naegele",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ScrollDisabler />

      <body className={`${mainFont.className} h-svh w-svw `}>
        <Navbar />
        <main className="">{children}</main>
      </body>
    </html>
  );
}
